// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlbumCardController from "./album_card_controller"
application.register("album-card", AlbumCardController)

import AlbumToggleController from "./album_toggle_controller"
application.register("album-toggle", AlbumToggleController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImportFormController from "./import_form_controller"
application.register("import-form", ImportFormController)

import RubyUi__CollapsibleController from "./ruby_ui/collapsible_controller"
application.register("ruby-ui--collapsible", RubyUi__CollapsibleController)

import RubyUi__ComboboxController from "./ruby_ui/combobox_controller"
application.register("ruby-ui--combobox", RubyUi__ComboboxController)

import RubyUi__DialogController from "./ruby_ui/dialog_controller"
application.register("ruby-ui--dialog", RubyUi__DialogController)

import RubyUi__DropdownMenuController from "./ruby_ui/dropdown_menu_controller"
application.register("ruby-ui--dropdown-menu", RubyUi__DropdownMenuController)

import RubyUi__FormFieldController from "./ruby_ui/form_field_controller"
application.register("ruby-ui--form-field", RubyUi__FormFieldController)

import RubyUi__PopoverController from "./ruby_ui/popover_controller"
application.register("ruby-ui--popover", RubyUi__PopoverController)

import RubyUi__ToastController from "./ruby_ui/toast_controller"
application.register("ruby-ui--toast", RubyUi__ToastController)

import RubyUi__ToasterController from "./ruby_ui/toaster_controller"
application.register("ruby-ui--toaster", RubyUi__ToasterController)
